Viweb\NewsBundle\Entity\CategoryTranslation:
    type: entity
    table: null
    repositoryClass: Viweb\NewsBundle\Repository\CategoryTranslationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
            nullable: true
        slug:
            type: string
            length: 255
    lifecycleCallbacks: {  }
