viweb_admin_news:
    resource: |
        alias: viweb.news
        redirect: update
        except: ['show', 'update']
        section: admin
        templates: ViwebSystemBundle:Crud
        grid: viweb_news
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'outline'
    type: sylius.resource
viweb_admin_news_update:
    path: /news/{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: viweb.controller.news:updateAction
        _sylius:
            section: admin
            template: ViwebSystemBundle:Crud:update.html.twig

viweb_admin_news_category:
    resource: |
        alias: viweb.news_category
        redirect: update
        except: ['show', 'update']
        section: admin
        templates: ViwebSystemBundle:Crud
        grid: viweb_news_category
        vars:
            all:
                subheader: app.ui.supplier
            index:
                icon: 'outline'
    type: sylius.resource

viweb_admin_news_category_update:
    path: /news/categorys/{id}/edit
    methods: [GET, POST]
    defaults:
        _controller: viweb.controller.categories:updateAction
        _sylius:
            section: admin
            template: ViwebSystemBundle:Crud:update.html.twig
