<?php

namespace Viweb\NewsBundle\Repository;

/**
 * NewsTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
